version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: /usr/local/bin/av1-encoder-service
        expose:
            - 8000
        env_file:
            - .env
        deploy:
            resources:
                limits:
                    memory: 1G
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web
